# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='address',
            name='test_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
