# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='key',
            field=models.CharField(max_length=128),
        ),
    ]
