# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_user_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uprn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=512)),
                ('parent_address_name', models.CharField(max_length=512)),
                ('street_name', models.CharField(max_length=512)),
                ('street_town', models.CharField(max_length=512)),
            ],
        ),
    ]
