# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20160917_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
